# Courses {#courses}

Edit this file [here](https://github.com/atacamagroup/handbook/blob/master/04-courses.Rmd).

## Textbooks

[Repository of statistics and programming books](https://www.dropbox.com/sh/mea9q94nletfsdy/AACD5QC_-RZKfBakR6qSXVrSa?dl=0)
from biostatistics graduate student group at Vanderbilt.

## Bioinformatics and Computational Biology

These are courses underneath the Bioinformatics and Computational Biomedicine
(BCB) program.

General piece of advice is to establish a study group to help bounce around
ideas and clarify concepts in a discussion. **Note**, this still means you are
responsible for doing and completing your own homework.

The study group is recommended because of the variety of topics you'll cover
and the variety of background your peers possess. There is bound to be a peer
of yours that is, say, more skilled in programming that you. But then you may
have the upper hand in genetics. Sharing knowledge amongst your peers will
ultimately help you all collectively in the end.

### BMI 551/651 Statistical Methods

Download
["An Introduction to Statistical Learning with Applications in R"](http://www-bcf.usc.edu/~gareth/ISL/).
It's a easier transition to learning statistical methods and contains R code
for you to further experiment and learn from.

If you feel more statistically and mathematically inclined, the
["The Elements of Statistical Learning: Data Mining, Inference, and Prediction"](https://web.stanford.edu/~hastie/ElemStatLearn/)
textbook is also available. It contains similar content to the introduction
text, but without the R code or easier to approach explanations.

### BMI 565/656 Programming and Scripting

There is [Python Tutor](http://pythontutor.com/) to help visualize how and
what your computer is doing when it executes code. May help lower the barrier
to learning programming.

### Miscellaneous

Here are some resources that are generally useful:

- [Modern Statistics for Modern Biology](http://web.stanford.edu/class/bios221/book/) -
  Aim of book is to get scientists working quickly to make best of data.
- [PH525x Series - Biomedical Data Science](http://genomicsclass.github.io/book/) -
  Book focuses on performing data analysis in genomics.
- [The Bioconductor 2018 Workshop Compilation](https://bioconductor.github.io/BiocWorkshops/) -
  Bioconductor workshop materials as a book for various genomics analyses,
  ranging from beginner users to expert users who contribute packages.

## Clinical Informatics

These are courses underneath the Health and Clinical Informatics (HCIN)
program.

### Miscellaneous

[Health Informatics Forum](http://healthinformaticsforum.com/) is an online
community and educational portal for health informatics professionals and
students. It contains lists of resources and it's own
[massive open online course (MOOC)](http://healthinformaticsforum.com/mooc).

## Fellows Meeting

For PhD students and post-docs, think of this time as having over 20 or so
human hours of attention given to you if you are presenting. Attention is our
more precious resource. Use it wisely.

## Computer Science

TODO

## PSU Computer Science

TODO

## PSU Statistics

TODO

## Independent Study

TODO
