# Research {#research}

## General Graduate School Advice

- [Tips for PhD Students by Claes Backman](https://sites.google.com/view/claesbackman/tips-for-phd-students)
- [How to Be a Successful PhD Student (in Computer Science in NLP/ML)](https://people.cs.umass.edu/~wallach/how_to_be_a_successful_phd_student.pdf) (PDF)
- [Tips for PhD students and early-career researchers by Mick Watson](http://www.opiniomics.org/tips-for-phd-students-and-early-career-researchers/)
- [Advice for early-stage Ph.D. students by Philip Guo](http://www.pgbovine.net/early-stage-PhD-advice.htm)
- [Surviving a PhD - 10 Top Tips by Alex Hope](https://thesiswhisperer.com/2012/07/16/surviving-a-phd-10-top-tips/)
- [Completing Your Dissertation: Strategies for Success by S.A. Koblinsky, J. Leichty, and C. Schull](https://sph.umd.edu/sites/default/files/files/StrategiesDissertationCompletion3_8_07.pdf) (PDF)
- [15 Tips For PhD Students In Their First Week](https://www.nextscientist.com/15-tips-phd-students-start/)
- [What to Look (Out) for in a PhD Advisor](https://authenticallyaverage.com/2019/10/15/what-to-look-out-for-in-a-phd-advisor/)

### Work-life balance

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I&#39;ve spent a lot of time this week thinking about the transient nature of social support that really is a hallmark of <a href="https://twitter.com/hashtag/phdlife?src=hash&amp;ref_src=twsrc%5Etfw">#phdlife</a> as an early career academic. As a graduate student, the friends you make are virtually guaranteed to leave at regular intervals. 1/n</p>&mdash; Katie Grogan 👩‍🔬🧬 (@Dr_KatieG1) <a href="https://twitter.com/Dr_KatieG1/status/1177961427459608578?ref_src=twsrc%5Etfw">September 28, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Dealing with failure/rejections

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I had a major rejection this week, was plagiarized earlier this month, and still feel like I’ve had a happy and productive month. I’d like to share my rejection rituals with y’all, since this is common. 1/7</p>&mdash; Dr. Calla Hummel (@CallaHummel) <a href="https://twitter.com/CallaHummel/status/1177240569522860033?ref_src=twsrc%5Etfw">September 26, 2019</a></blockquote>

## Reading Journal Articles

- [Ten simple rules for developing good reading habits during graduate school and beyond (2018)](https://doi.org/10.1371/journal.pcbi.1006467)
- [How to Read a Paper](http://blizzard.cs.uwaterloo.ca/keshav/home/Papers/data/07/paper-reading.pdf) - Suggests a three-pass method to reading research papers, each pass increasing the depth of details you read into

## Performing dissertation literature review

- [Randolph. "A Guide to Writing the Dissertation Literature Review" (2009)](http://lemass.net/capstone/files/A%20Guide%20to%20Writing%20the%20Dissertation%20Literature%20Review.pdf) (PDF)

Consider using the [matrix method](https://guides.library.duq.edu/matrix) to organize your reviewed sources.

To begin, start with three columns:

| Authors, title, journal                                      | Year Pub | Purpose                                                    |
|--------------------------------------------------------------|----------|------------------------------------------------------------|
| Martin, JE et al. "A DNA vaccina for Ebola virus is safe..." | 2006     | Determine safety and immunogenicity of Ebola vaccine in... |

Here are [some templates](https://academicguides.waldenu.edu/writingcenter/assignments/literaturereview/matrix).

## Keeping Up with Literature

- [PubChase](https://www.pubchase.com/)
- [Google Scholar Alerts](https://scholar.google.com/)
- Follow academic leaders in your field on Twitter
- [Staying Current in Bioinformatics & Genomics: 2017 Edition](https://www.gettinggeneticsdone.com/2017/02/staying-current-in-bioinformatics-genomics-2017.html)

It is not recommended to use [Sci-Hub](https://www.sciencemag.org/news/2017/07/sci-hub-s-cache-pirated-papers-so-big-subscription-journals-are-doomed-data-analyst) to quickly and easily access almost all of science.

## Writing

General tips:

- [Ten Simple Rules for Writing Research Papers](https://doi.org/10.1371/journal.pcbi.1003453)
- [Ten Simple Rules for Writing a Literature Review](https://doi.org/10.1371/journal.pcbi.1003149)

If you use Emacs, you can use the [Academic-phrases package](https://github.com/nashamri/academic-phrases) to help write phrases typical of academic papers. A list of these phrases can be found at the [bottom of this page](https://www.springer.com/gb/book/9783319260921) in a link titled, "Free Download: Useful Phrases".

Thread on writing from a writer:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I was asked today how I manage to write novels while working full time, and since work is a little quiet today (oh the irony), I thought I&#39;d share the answer with you guys: small, achievable goals.<br><br>A thread.</p>&mdash; Kate Dylan (@TheKateDylan) <a href="https://twitter.com/TheKateDylan/status/1074510080484139008?ref_src=twsrc%5Etfw">December 17, 2018</a></blockquote>

## Bibliography Management

- [Zotero](http://zotero.org/) (Open source cross-platform)
  - [Quick start guide](https://www.zotero.org/support/quick_start_guide)
- [Mendeley](https://www.mendeley.com/) (Commercial)
- [`org-ref`](https://github.com/jkitchin/org-ref) (Emacs)
- [EndNote](https://endnote.com/) (Commercial)

## Conferences

If running on a budget,
look for opportunities to volunteer at conferences.
It is a good way to mean other graduate students or other early career
researchers and learn how conferences are hosted.

Also look for student discounts if possible.
If there are none listed,
don't be afraid to email the conference organizers to see if there is a student
discount.

Locally, you can also apply for travel awards through the
[Graduate Student Organization (GSO)](https://ohsugso.weebly.com/gso-travel-award.html).
The deadline to apply is the term before your anticipated travel.

Some nearby and prominent conferences to consider:

- [Institute of Systems Biology (ISB) Symposium](https://systemsbiology.org/symposium/) (Seattle, WA) - Around April, two days, around $50 for students and postdocs.
- [Pacific Symposium on Biocomputing (PSB)](https://psb.stanford.edu/) (Hawaii) - Around January, submit proceedings to be publication.
- [rstudio::conf](https://www.rstudio.com/conference/) - Around January, the 2020 conference is in San Francisco, CA.
- [American Medical Informatics Association (AMIA)](https://www.amia.org/)
- [Health Information and Management Systems Society (HIMSS)](https://www.himss.org/)

## Conference Posters

Some tips from
[Hello PhD](http://hellophd.com/2018/11/104-how-to-give-a-perfect-poster-presentation/)
on making poster presentations:

- In preparation
    - Know your audience
    - Start early
    - Practice
    - Find your story
- Presenting
    - Timing is everything
    - Act like an actor and show enthusiasm
    - Personalize your pitch based on your audience's background

Feel free to also skim through https://betterposters.blogspot.com/,
a blog for advice and critiques on making better scientific posters.

### Poster Templates

**Better Scientific Poster**

A novel poster format, dubbed the "better scientific poster", has been created
and a template of it can be found [here](https://osf.io/ef53g/).

**posterdown**

Use RMarkdown to generate PDF Conference Posters via HTML or LaTeX
https://github.com/brentthorne/posterdown.

## Applications

Here is a repository of successful job and grant applications that may be
helpful https://github.com/RILAB/statements.

## Modern Scientist

"How to be a modern scientist" is an affordable book by Jeff Leek on how to
navigate the academic world (e.g., publishing, data sharing, blogging, etc.).

Website: https://leanpub.com/modernscientist

Description:

> The face of academia is changing. It is no longer sufficient to just publish
> or perish. We are now in an era where Twitter, Github, Figshare, and Alt
> Metrics are regular parts of the scientific workflow. Here I give high level
> advice about which tools to use, how to use them, and what to look out for.
> This book is appropriate for scientists at all levels who want to stay on top
> of the current technological developments affecting modern scientific
> careers.

## NLM and NIH Fellows

This doesn't directly apply to trainees, but this site is a nice reference to
have when reviewing the terms of the fellowship
https://www.nlm.nih.gov/ep/trainingdirectors.html.

## Miscellaneous Research

Curated list of tools to help with research
https://github.com/emptymalei/awesome-research.

Excellent blog dedicated to the topic of doing a PhD and completing a
dissertation https://thesiswhisperer.com/. Extensive catelog of blog posts with
valuable advice and links to useful resources, ranging from writing advice and
presentation advice to dealing with academia and post-graduate school career
hunting. Advice is directed towards PhD students, but it is helpful for all
students.

[Resources for people of color (POCs) in STEAM](https://docs.google.com/spreadsheets/d/1V_pvhqWliwqLhAVcXikxAEuJPD4mwwgl9LEgOnzN-zM/edit?usp=sharing)
